# Generated by Django 4.2.30 on 2026-08-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_activitytype_classactivity_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
