# Generated by Django 4.2.30 on 2026-08-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_feepayment'),
        ('courses', '0024_conversationmessage_attachment_and_more'),
    ]

    operations = [
    ]
