# Generated by Django 4.2.30 on 2026-08-14 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_odrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0002_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('not_cleared', 'Not cleared'), ('waiting_list', 'Waiting list'), ('absent', 'Absent')], default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='placement.application')),
                ('drive_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='placement.driveround')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_results_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['drive_round__order', 'application__student__roll_number'],
            },
        ),
        migrations.CreateModel(
            name='DriveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_attendance', to='placement.application')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('od_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_attendances', to='attendance.odrequest')),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roundresult',
            constraint=models.UniqueConstraint(fields=('application', 'drive_round'), name='unique_result_per_application_round'),
        ),
    ]
