# Generated by Django 4.2.30 on 2026-08-18 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement', '0003_roundresult_driveattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='offered', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('offered_on', models.DateField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='placement.application')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-offered_on'],
            },
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='application',
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='drive_round',
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='eligibilityrule',
            name='allow_already_placed',
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='placed_package_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='DriveRound',
        ),
        migrations.DeleteModel(
            name='RoundResult',
        ),
    ]
